articles_index:
    path:     /
    defaults: { _controller: "AppBundle:Article:index" }
    methods:  GET

articles_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Article:show" }
    methods:  GET

articles_new:
    path:     /new
    defaults: { _controller: "AppBundle:Article:new" }
    methods:  [GET, POST]

articles_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Article:edit" }
    methods:  [GET, POST]

articles_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Article:delete" }
    methods:  DELETE

autors_index:
    path:     /authors
    defaults: { _controller: "AppBundle:Author:index" }
    methods:  GET

autors_new:
    path:     /authors/new
    defaults: { _controller: "AppBundle:Author:new" }
    methods:  [GET, POST]